# Generated by Django 5.1 on 2024-11-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
